import React, { useState } from "react";
import { createRoot } from "react-dom/client";

function SeverityBadge({s}) {
  const color = s==="CRITICAL"?"#b91c1c": s==="HIGH"?"#f97316": s==="MEDIUM"?"#f59e0b":"#10b981";
  return <span style={{background:color,color:"#fff",padding:"4px 8px",borderRadius:6,fontSize:12}}>{s}</span>
}

function App(){
  const [report, setReport] = useState(null);

  async function handleFile(e){
    const f = e.target.files[0];
    if(!f) return;
    const text = await f.text();
    setReport(JSON.parse(text));
  }

  return (
    <div style={{fontFamily:"Inter, sans-serif",padding:24,background:"#0f172a",minHeight:"100vh",color:"#e6eef8"}}>
      <h1>SVDF Dashboard</h1>
      <p>Load a report JSON generated by the CLI.</p>
      <input type="file" onChange={handleFile} />
      {!report && <p style={{opacity:0.7}}>No report loaded yet.</p>}
      {report && (
        <>
          <h2>Summary</h2>
          <div style={{display:"flex",gap:20}}>
            <div style={{background:"#020617",padding:12,borderRadius:8}}>
              <div>Target</div>
              <div style={{fontWeight:700}}>{report.target}</div>
            </div>
            <div style={{background:"#020617",padding:12,borderRadius:8}}>
              <div>Static Findings</div>
              <div style={{fontWeight:700}}>{report.static_findings.length}</div>
            </div>
            <div style={{background:"#020617",padding:12,borderRadius:8}}>
              <div>Fuzzer Crashes</div>
              <div style={{fontWeight:700}}>{report.fuzzer_crashes.length}</div>
            </div>
          </div>

          <h3 style={{marginTop:20}}>Static Findings</h3>
          <div>
            {report.static_findings.map((f,idx)=>(
              <div key={idx} style={{background:"#07102a",padding:12,borderRadius:8,marginBottom:8,display:"flex",justifyContent:"space-between"}}>
                <div>
                  <div style={{fontWeight:700}}>{f.file}:{f.line}</div>
                  <div style={{opacity:0.9}}>{f.message} — <code style={{background:"#020617",padding:"2px 6px",borderRadius:4}}>{f.snippet}</code></div>
                  <div style={{marginTop:6,opacity:0.8}}><small>Fix: {f.suggested_fix}</small></div>
                </div>
                <div style={{textAlign:"right"}}>
                  <SeverityBadge s={f.severity} />
                </div>
              </div>
            ))}
          </div>

          <h3 style={{marginTop:20}}>Fuzzer Crashes</h3>
          <div>
            {report.fuzzer_crashes.length===0 && <div style={{opacity:0.7}}>No crashes found.</div>}
            {report.fuzzer_crashes.map((c,idx)=>(
              <div key={idx} style={{background:"#07102a",padding:12,borderRadius:8,marginBottom:8}}>
                <div><strong>Input:</strong> {c.input}</div>
                <div><strong>Log:</strong> {c.log}</div>
                <div><strong>Return code:</strong> {c.rc}</div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

createRoot(document.getElementById("root")).render(<App />);
export default App;
